import l1 from "../ExampleDB/laptops_imgs/Lenovo ThinkPad X1 Carbon Gen 11.jpg";
import l2 from "../ExampleDB/laptops_imgs/Dell Latitude 7440.jpg";
import l3 from "../ExampleDB/laptops_imgs/HP EliteBook 840 G9.jpeg";
import l4 from "../ExampleDB/laptops_imgs/Microsoft Surface Laptop 5.jpg";
import l5 from "../ExampleDB/laptops_imgs/ASUS ROG Zephyrus G14.jpg";
import l6 from "../ExampleDB/laptops_imgs/MSI Katana GF66.jpg";
import l7 from "../ExampleDB/laptops_imgs/Alienware m18.jpg";
import l8 from "../ExampleDB/laptops_imgs/Lenovo Legion Pro 5.jpg";
import l9 from "../ExampleDB/laptops_imgs/HP Spectre x360 14.jpg";
import l10 from "../ExampleDB/laptops_imgs/Lenovo Yoga 9i Gen 8.jpg";
import l11 from "../ExampleDB/laptops_imgs/Dell XPS 13 2-in-1.jpg";
import l12 from "../ExampleDB/laptops_imgs/Microsoft Surface Pro 9.jpg";
import l13 from "../ExampleDB/laptops_imgs/Google Pixelbook Go.jpg";
import l14 from "../ExampleDB/laptops_imgs/Lenovo Chromebook Duet 3.jpg";
import l15 from "../ExampleDB/laptops_imgs/HP Chromebook x360 14c.jpg";
import l16 from "../ExampleDB/laptops_imgs/Acer Chromebook Spin 713.jpg";
import l17 from "../ExampleDB/laptops_imgs/Dell Precision 5680.jpg";
import l18 from "../ExampleDB/laptops_imgs/Lenovo ThinkPad P1 Gen 6.jpg";
import l19 from "../ExampleDB/laptops_imgs/HP ZBook Power G9.jpg";
import l20 from "../ExampleDB/laptops_imgs/Apple MacBook Pro 16-inch (M2 Max).jpg";
import l21 from "../ExampleDB/laptops_imgs/Apple MacBook Air (M2).jpg";
import l22 from "../ExampleDB/laptops_imgs/Dell XPS 13.jpg";
import l23 from "../ExampleDB/laptops_imgs/ASUS Zenbook S 13 OLED (UX5304).jpg";
import l24 from "../ExampleDB/laptops_imgs/LG Gram 16.jpg";
export const laptops = [
  {
    name: "Lenovo ThinkPad X1 Carbon Gen 11",
    brand: "Lenovo",
    category: "business",
    price: 1899,
    img: l1,
    diagonal: 14,
    cpu: "Intel Core i7-1365U",
    gpu: "Intel Iris Xe Graphics",
    ram: "16GB",
    weight: 1.12,
    seller: "LapTech",
    rating: 4.8,
  },
  {
    name: "Dell Latitude 7440",
    brand: "Dell",
    category: "business",
    price: 1650,
    img: l2,
    diagonal: 14,
    cpu: "Intel Core i5-1335U",
    gpu: "Intel Iris Xe Graphics",
    ram: "8GB",
    weight: 1.27,
    seller: "TechGuru",
    rating: 4.5,
  },
  {
    name: "HP EliteBook 840 G9",
    brand: "HP",
    category: "business",
    price: 1720,
    img: l3,
    diagonal: 14,
    cpu: "Intel Core i7-1265U",
    gpu: "Intel Iris Xe Graphics",
    ram: "16GB",
    weight: 1.32,
    seller: "ElectroWorld",
    rating: 4.7,
  },
  {
    name: "Microsoft Surface Laptop 5",
    brand: "Microsoft",
    category: "business",
    price: 1550,
    img: l4,
    diagonal: 13.5,
    cpu: "Intel Core i5-1235U",
    gpu: "Intel Iris Xe Graphics",
    ram: "8GB",
    weight: 1.27,
    seller: "LapTech",
    rating: 4.6,
  },

  // Gaming (4)
  {
    name: "ASUS ROG Zephyrus G14",
    brand: "ASUS",
    category: "gaming",
    price: 2100,
    img: l5,
    diagonal: 14,
    cpu: "AMD Ryzen 9 7940HS",
    gpu: "NVIDIA GeForce RTX 4060",
    ram: "16GB",
    weight: 1.65,
    seller: "TechGuru",
    rating: 4.9,
  },
  {
    name: "MSI Katana GF66",
    brand: "MSI",
    category: "gaming",
    price: 1450,
    img: l6,
    diagonal: 15.6,
    cpu: "Intel Core i7-12700H",
    gpu: "NVIDIA GeForce RTX 3050 Ti",
    ram: "16GB",
    weight: 2.25,
    seller: "ElectroWorld",
    rating: 4.4,
  },
  {
    name: "Alienware m18",
    brand: "Alienware",
    category: "gaming",
    price: 2800,
    img: l7,
    diagonal: 18,
    cpu: "Intel Core i9-13900HX",
    gpu: "NVIDIA GeForce RTX 4080",
    ram: "32GB",
    weight: 3.63,
    seller: "LapTech",
    rating: 4.8,
  },
  {
    name: "Lenovo Legion Pro 5",
    brand: "Lenovo",
    category: "gaming",
    price: 1950,
    img: l8,
    diagonal: 16,
    cpu: "AMD Ryzen 7 7745HX",
    gpu: "NVIDIA GeForce RTX 4070",
    ram: "16GB",
    weight: 2.5,
    seller: "TechGuru",
    rating: 4.7,
  },

  // 2 in 1 (4)
  {
    name: "HP Spectre x360 14",
    brand: "HP",
    category: "2 in 1",
    price: 1500,
    img: l9,
    diagonal: 13.5,
    cpu: "Intel Core i7-1355U",
    gpu: "Intel Iris Xe Graphics",
    ram: "16GB",
    weight: 1.36,
    seller: "ElectroWorld",
    rating: 4.6,
  },
  {
    name: "Lenovo Yoga 9i Gen 8",
    brand: "Lenovo",
    category: "2 in 1",
    price: 1680,
    img: l10,
    diagonal: 14,
    cpu: "Intel Core i7-1360P",
    gpu: "Intel Iris Xe Graphics",
    ram: "16GB",
    weight: 1.4,
    seller: "LapTech",
    rating: 4.7,
  },
  {
    name: "Dell XPS 13 2-in-1 (9315)",
    brand: "Dell",
    category: "2 in 1",
    price: 1400,
    img: l11,
    diagonal: 13,
    cpu: "Intel Core i5-1230U",
    gpu: "Intel Iris Xe Graphics",
    ram: "8GB",
    weight: 0.74,
    seller: "TechGuru",
    rating: 4.5,
  },
  {
    name: "Microsoft Surface Pro 9",
    brand: "Microsoft",
    category: "2 in 1",
    price: 1350,
    img: l12,
    diagonal: 13,
    cpu: "Intel Core i5-1245U",
    gpu: "Intel Iris Xe Graphics",
    ram: "8GB",
    weight: 0.88,
    seller: "ElectroWorld",
    rating: 4.4,
  },

  // Chromebook (4)
  {
    name: "Google Pixelbook Go",
    brand: "Google",
    category: "chromebook",
    price: 800,
    img: l13,
    diagonal: 13.3,
    cpu: "Intel Core i5",
    gpu: "Intel UHD Graphics",
    ram: "8GB",
    weight: 1.06,
    seller: "LapTech",
    rating: 4.3,
  },
  {
    name: "Lenovo Chromebook Duet 3",
    brand: "Lenovo",
    category: "chromebook",
    price: 400,
    img: l14,
    diagonal: 11,
    cpu: "MediaTek Helio P60T",
    gpu: "Integrated Graphics",
    ram: "4GB",
    weight: 0.52,
    seller: "TechGuru",
    rating: 4.2,
  },
  {
    name: "HP Chromebook x360 14c",
    brand: "HP",
    category: "chromebook",
    price: 650,
    img: l15,
    diagonal: 14,
    cpu: "Intel Core i3-1115G4",
    gpu: "Intel UHD Graphics",
    ram: "8GB",
    weight: 1.56,
    seller: "ElectroWorld",
    rating: 4.1,
  },
  {
    name: "Acer Chromebook Spin 713",
    brand: "Acer",
    category: "chromebook",
    price: 750,
    img: l16,
    diagonal: 13.5,
    cpu: "Intel Core i5-1135G7",
    gpu: "Intel Iris Xe Graphics",
    ram: "8GB",
    weight: 1.37,
    seller: "LapTech",
    rating: 4.4,
  },

  // Workstation (4)
  {
    name: "Dell Precision 5680",
    brand: "Dell",
    category: "workstation",
    price: 2500,
    diagonal: 16,
    img: l17,
    cpu: "Intel Core i9-13900H",
    gpu: "NVIDIA RTX A2000",
    ram: "32GB",
    weight: 1.92,
    seller: "TechGuru",
    rating: 4.9,
  },
  {
    name: "Lenovo ThinkPad P1 Gen 6",
    brand: "Lenovo",
    category: "workstation",
    price: 2300,
    img: l18,
    diagonal: 16,
    cpu: "Intel Core i7-13700H",
    gpu: "NVIDIA RTX A1000",
    ram: "16GB",
    weight: 1.79,
    seller: "ElectroWorld",
    rating: 4.8,
  },
  {
    name: "HP ZBook Power G9",
    brand: "HP",
    category: "workstation",
    price: 2150,
    img: l19,
    diagonal: 15.6,
    cpu: "Intel Core i7-12800H",
    gpu: "NVIDIA RTX A500",
    ram: "16GB",
    weight: 1.9,
    seller: "LapTech",
    rating: 4.7,
  },
  {
    name: "Apple MacBook Pro 16-inch (M2 Max)",
    brand: "Apple",
    category: "workstation",
    price: 3500,
    img: l20,
    diagonal: 16.2,
    cpu: "Apple M2 Max",
    gpu: "Integrated Apple Graphics",
    ram: "32GB",
    weight: 2.16,
    seller: "TechGuru",
    rating: 4.9,
  },

  // Ultrabook (4)
  {
    name: "Apple MacBook Air (M2)",
    brand: "Apple",
    category: "ultrabook",
    price: 1200,
    img: l21,
    diagonal: 13.6,
    cpu: "Apple M2",
    gpu: "Integrated Apple Graphics",
    ram: "8GB",
    weight: 1.24,
    seller: "ElectroWorld",
    rating: 4.8,
  },
  {
    name: "Dell XPS 13 (9315)",
    brand: "Dell",
    category: "ultrabook",
    price: 1300,
    img: l22,
    diagonal: 13.4,
    cpu: "Intel Core i5-1230U",
    gpu: "Intel Iris Xe Graphics",
    ram: "8GB",
    weight: 1.17,
    seller: "LapTech",
    rating: 4.7,
  },
  {
    name: "ASUS Zenbook S 13 OLED (UX5304)",
    brand: "ASUS",
    category: "ultrabook",
    price: 1450,
    img: l23,
    diagonal: 13.3,
    cpu: "Intel Core i7-1355U",
    gpu: "Intel Iris Xe Graphics",
    ram: "16GB",
    weight: 1,
    seller: "TechGuru",
    rating: 4.9,
  },
  {
    name: "LG Gram 16",
    brand: "LG",
    category: "ultrabook",
    price: 1350,
    img: l24,
    diagonal: 16,
    cpu: "Intel Core i5-1340P",
    gpu: "Intel Iris Xe Graphics",
    ram: "16GB",
    weight: 1.19,
    seller: "ElectroWorld",
    rating: 4.6,
  },
];
